on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.password}}
    - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/webpages .
    - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/webpages:latest
    - run: echo "my task is finished"
